<?php

declare(strict_types=1);

namespace Tests\Import\Importers;

use Daycry\Iban\Contracts\ImporterInterface;
use Daycry\Iban\Import\Importers\BundesbankImporter;
use PHPUnit\Framework\TestCase;

/**
 * Exercises {@see BundesbankImporter} in isolation (plain PHPUnit,
 * framework-free) against the hand-crafted fixed-width fixture
 * `tests/Fixtures/import/bundesbank_sample.txt`, built to the exact
 * 168-char record layout documented in the Deutsche Bundesbank's official
 * "Merkblatt Bankleitzahlendatei" (Stand: 20. Dezember 2022), Anhang 1.
 *
 * @see \Daycry\Iban\Import\Importers\BundesbankImporter
 */
final class BundesbankImporterTest extends TestCase
{
    private const FIXTURE = __DIR__ . '/../../Fixtures/import/bundesbank_sample.txt';

    private BundesbankImporter $importer;

    protected function setUp(): void
    {
        parent::setUp();

        $this->importer = new BundesbankImporter();
    }

    public function testImplementsImporterInterface(): void
    {
        self::assertInstanceOf(ImporterInterface::class, $this->importer);
    }

    public function testMetadataIsAsDocumented(): void
    {
        self::assertSame('DE', $this->importer->countryCode());
        self::assertSame('bundesbank', $this->importer->sourceId());
        self::assertSame('Deutsche Bundesbank', $this->importer->sourceName());
        self::assertSame('Deutsche Bundesbank', $this->importer->license());
        self::assertStringStartsWith('https://www.bundesbank.de/', $this->importer->sourceUrl());
    }

    public function testLicenseFitsTheSourceLicenseColumnWidth(): void
    {
        // `banks.source_license` is VARCHAR(64) -- a longer string would be
        // silently truncated by the database (see ImportRunner/CreateBanksTable).
        self::assertLessThanOrEqual(64, strlen($this->importer->license()));
    }

    public function testRowsYieldsOnlyMerkmalOneRecordsFromTheFixture(): void
    {
        $rows = iterator_to_array($this->importer->rows(self::FIXTURE), false);

        // The fixture has 4 fixed-width lines, read in this order: a
        // Merkmal '1' (principal) record for BLZ 37040044, then a Merkmal
        // '2' (subordinate) record for that SAME BLZ -- which must be
        // skipped -- then a second Merkmal '1' record for BLZ 50010517,
        // then a third Merkmal '1' record for BLZ 16050202 (used to prove
        // the ISO-8859-1 -> UTF-8 decoding below). So exactly 3 rows are
        // yielded, in this order.
        self::assertCount(3, $rows);

        $commerzbank = $rows[0];
        self::assertSame('37040044', $commerzbank['bank_code']);
        self::assertSame('Commerzbank', $commerzbank['name']);
        self::assertSame('Commerzbank Essen', $commerzbank['short_name']);
        self::assertSame('Essen', $commerzbank['city']);
        self::assertSame('COBADEFFXXX', $commerzbank['bic']);
        self::assertNull($commerzbank['branch_code']);

        $ingDiba = $rows[1];
        self::assertSame('50010517', $ingDiba['bank_code']);
        self::assertSame('ING-DiBa', $ingDiba['name']);
        self::assertSame('ING-DiBa Frankfurt', $ingDiba['short_name']);
        self::assertSame('Frankfurt am Main', $ingDiba['city']);
        self::assertSame('INGDDEFFXXX', $ingDiba['bic']);
    }

    /**
     * The Bundesbank Bankleitzahlendatei is published in ISO-8859-1
     * (Latin-1), not UTF-8. This fixture's 4th line was generated by a
     * one-off PHP script (not typed in a UTF-8 editor) that wrote the "ü" in
     * "Lübben" as the single raw Latin-1 byte 0xFC, so the record stays
     * exactly 168 bytes wide and every field offset after it is unaffected.
     * `rows()` must decode each extracted field from ISO-8859-1 to UTF-8
     * AFTER slicing -- converting the whole line first would turn 0xFC into
     * a 2-byte UTF-8 sequence and shift every subsequent `substr()` offset.
     */
    public function testRowsDecodesIso88591UmlautsToUtf8(): void
    {
        $rows = iterator_to_array($this->importer->rows(self::FIXTURE), false);

        $sparkasse = $rows[2];
        self::assertSame('16050202', $sparkasse['bank_code']);
        self::assertSame('Lübben', $sparkasse['city']);
        self::assertSame('Sparkasse Niederlausitz', $sparkasse['name']);
        self::assertSame('Spk Niederlausitz Lübben', $sparkasse['short_name']);
        self::assertTrue(mb_check_encoding($sparkasse['city'], 'UTF-8'));
    }

    public function testFixtureUmlautLineIsExactly168BytesOfRawLatin1(): void
    {
        // Guards the fixture itself: confirms line 4 is genuinely a single
        // raw Latin-1 byte (0xFC), not a multi-byte UTF-8 "ü" that would
        // silently shift every subsequent field's offset.
        $lines = preg_split('/\r\n|\r|\n/', (string) file_get_contents(self::FIXTURE));
        self::assertIsArray($lines);
        $umlautLine = $lines[3];

        self::assertSame(168, strlen($umlautLine));
        self::assertStringContainsString("\xFC", $umlautLine);
    }

    public function testRowsReturnsEmptyIterableWhenTheFileCannotBeRead(): void
    {
        $rows = iterator_to_array($this->importer->rows('/nonexistent/path/blz.txt'), false);

        self::assertSame([], $rows);
    }
}
