<?php

declare(strict_types=1);

namespace Daycry\Iban\Import\Importers;

use Daycry\Iban\Contracts\ImporterInterface;
use Daycry\Iban\Import\Importers\Concerns\ReadsXlsxSource;

/**
 * Official-source importer for Luxembourg (LU): the ABBL's (Association des
 * Banques et Banquiers, Luxembourg) "Luxembourg Register of IBAN/BIC Codes"
 * -- the authoritative registry of every 3-digit bank code (this source's
 * `bank_code`, the segment a Luxembourg IBAN's BBAN starts with) assigned to
 * a Luxembourg credit institution.
 *
 * - Live source: {@see self::sourceUrl()} is the STABLE landing page --
 *   confirmed live on 2026-07-11 that the actual download is a per-request,
 *   ROTATING URL generated by the page (e.g.
 *   `https://office-membernet.abbl.lu/newDocRequest/<token>/ABBL_...xlsx`),
 *   not a fixed file location. A live `rows()` call therefore CANNOT resolve
 *   the landing page into the spreadsheet on its own -- fetch the current
 *   file manually and pass it via `iban:update --file=<path>` (or
 *   {@see self::rows()}'s `$localFile` parameter directly) for an offline
 *   import; this importer's `$localFile` code path is unaffected by the
 *   rotation. Automated tests exercise this importer exclusively via a
 *   hand-crafted fixture, never the live URL.
 * - Format (confirmed live via the rotating download on 2026-07-11): one
 *   preamble row (a multi-line title), then a header row with these EXACT
 *   column labels, INCLUDING their real leading/trailing whitespace --
 *   `Credit institution`, `IBAN Code ` (note the trailing space), `
 *   BIC Code` (note the leading space). Columns are matched by NAME (via
 *   {@see self::locateHeader()}, which trims each header cell before
 *   comparing), not position.
 * - Already bank-level, one row per institution -- there is no branch/
 *   head-office distinction to filter, and Luxembourg IBANs carry no branch
 *   segment (`branch_code` stays `null` here). No dedup is needed: every
 *   3-digit code in this list is unique.
 * - BIC normalization: the live file formats most BIC values with spaces
 *   between the SWIFT segments (e.g. `'BCEE LU LL'`), but not all (e.g.
 *   `'BAERLULU'`) -- {@see self::rows()} strips all internal whitespace so
 *   `bic` holds a canonical, space-free BIC in both cases.
 *
 * CAVEAT: parsing targets the documented/observed source format as of this
 * release -- validate against the live official file before production use;
 * issuing bodies change layouts without notice.
 *
 * FRAMEWORK-FREE: uses only native PHP (`file_get_contents()`) plus
 * {@see XlsxReader} (itself framework-free) to fetch/parse, per
 * {@see ImporterInterface}'s framework-free contract -- even though
 * `src/Import/` itself isn't covered by
 * `tests/Architecture/CoreIsFrameworkFreeTest.php`.
 *
 * @see \Daycry\Iban\Import\ImporterRegistry::registerDefaults()
 * @see docs/superpowers/specs/2026-07-10-daycry-iban-v1-design.md
 */
final class LuxembourgBankersAssociationImporter implements ImporterInterface
{
    use ReadsXlsxSource;

    private const BANK_CODE_PATTERN = '/^[0-9]{3}$/';

    public function countryCode(): string
    {
        return 'LU';
    }

    public function sourceId(): string
    {
        return 'abbl';
    }

    public function sourceName(): string
    {
        return 'ABBL (Luxembourg Register of IBAN/BIC)';
    }

    public function license(): string
    {
        return 'ABBL Luxembourg IBAN/BIC Register';
    }

    public function sourceUrl(): string
    {
        return 'https://www.abbl.lu/publications/abbl-luxembourg-register-of-iban-bic-codes/';
    }

    /**
     * @return iterable<array<string, mixed>>
     */
    public function rows(?string $localFile = null): iterable
    {
        // The landing page ({@see self::sourceUrl()}) never resolves to the
        // spreadsheet itself -- the real download is a rotating, per-request
        // URL the page generates. A live fetch would need that URL
        // discovered out-of-band, so this importer only supports offline
        // import (`$localFile`); a bare live call gracefully yields nothing
        // ({@see ReadsXlsxSource::readXlsxGrid()} returns `[]`) rather than
        // importing the landing page's HTML as bogus data.
        $grid = $this->readXlsxGrid($localFile, $this->sourceUrl());

        $header = self::locateHeader($grid);

        if ($header === null) {
            return;
        }

        [$headerRowIndex, $columns] = $header;

        for ($i = $headerRowIndex + 1, $count = count($grid); $i < $count; $i++) {
            $row      = $grid[$i];
            $bankCode = trim($row[$columns['code']] ?? '');

            if (preg_match(self::BANK_CODE_PATTERN, $bankCode) !== 1) {
                continue; // blank row or malformed data
            }

            yield [
                'bank_code'   => $bankCode,
                'branch_code' => null,
                'name'        => self::nullableTrim($row[$columns['name']] ?? ''),
                'bic'         => self::normalizeBic($row[$columns['bic']] ?? ''),
            ];
        }
    }

    /**
     * Scans `$grid` for the row carrying all three expected header cells --
     * `"Credit institution"`, `"IBAN Code"` and `"BIC Code"` (each compared
     * case-insensitively AFTER trimming, since the live file's header row
     * carries stray leading/trailing whitespace, e.g. `'IBAN Code '`) --
     * and returns its index plus a `name`/`code`/`bic` column-index map, or
     * `null` if no such row exists (e.g. an unexpected layout change).
     * Requiring all three in the SAME row is what keeps this from matching
     * the preamble title row, whose single populated cell contains "IBAN"
     * and "BIC" as part of a longer sentence, not as an exact trimmed label.
     *
     * @param list<list<string>> $grid
     *
     * @return array{0: int, 1: array{name: int, code: int, bic: int}}|null
     */
    private static function locateHeader(array $grid): ?array
    {
        foreach ($grid as $rowIndex => $row) {
            $nameColumn = null;
            $codeColumn = null;
            $bicColumn  = null;

            foreach ($row as $columnIndex => $cell) {
                $trimmed = trim($cell);

                if ($nameColumn === null && strcasecmp($trimmed, 'Credit institution') === 0) {
                    $nameColumn = $columnIndex;
                } elseif ($codeColumn === null && strcasecmp($trimmed, 'IBAN Code') === 0) {
                    $codeColumn = $columnIndex;
                } elseif ($bicColumn === null && strcasecmp($trimmed, 'BIC Code') === 0) {
                    $bicColumn = $columnIndex;
                }
            }

            if ($nameColumn !== null && $codeColumn !== null && $bicColumn !== null) {
                return [$rowIndex, ['name' => $nameColumn, 'code' => $codeColumn, 'bic' => $bicColumn]];
            }
        }

        return null;
    }

    private static function nullableTrim(string $value): ?string
    {
        $trimmed = trim($value);

        return $trimmed !== '' ? $trimmed : null;
    }

    private static function normalizeBic(string $value): ?string
    {
        $normalized = strtoupper(str_replace(' ', '', trim($value)));

        return $normalized !== '' ? $normalized : null;
    }
}
